version: 2.1

orbs: 
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.6
 
jobs:
  run-ui-tests:
    working_directory: ~/testing-task/UI-testing
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout:
          path: ~/testing-task
      - run: sudo apt-get update
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: install npm dependancies
          command:
            npm install
      - run:
          name: run ui tests
          command:
            npm run test
      - store_test_results: 
          path: /tests_output

  run-api-tests:
    working_directory: ~/testing-task/API-testing
    docker:
      - image: circleci/node:14
    steps:
      - checkout:
          path: ~/testing-task
      - run:
          name: install npm dependencies
          command:
            npm install
      - run:
          name: start mock-user-auth server
          command: npm run dev
          background: true
      - run:
          name: run tests
          command: npm run test
      - run:
          name: stop mock-user-auth server
          command: npm stop
      - store_test_results: 
          path: /tests_output

workflows:
  testing-workflow:
    jobs:
      - run-ui-tests
      - run-api-tests