version: 2.1

orbs: 
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.6
 
jobs:
  run-ui-tests:
    working_directory: ~/testing-task/UI-testing
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout:
          path: ~/testing-task
      - run: sudo apt-get update
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
      # - run:
      #     name: Fix PATH
      #     command: |
      #       echo "see https://github.com/CircleCI-Public/browser-tools-orb/blob/de5fa4e28909039438189815dbb42ac308e49bc9/src/scripts/install-chromedriver.sh#L187"
      #       echo "export PATH='/usr/local/bin/chromedriver:$PATH'" >> $BASH_ENV
      # - browser-tools/install-browser-tools:
          # chrome-version: 114.0.5735.90
      - run:
          name: install npm dependancies
          command:
            npm install
      - run:
          name: run ui tests
          command:
            npm run test
      - store_test_results: 
          path: /tests_output

workflows:
  testing-workflow:
    jobs:
      - run-ui-tests